#!/usr/bin/env python3
"""NO SUCH DAY — builds data.json, counts.json and index.html from the census.

    python3 build.py <census-output-dir>

The census files are not committed: they are 16 x 160 332 lines of answers,
regenerated by the scripts in census/ in a few seconds. What is committed is
this script, the numbers it derives, and the page it draws.
"""
import json, os, sys, hashlib
from collections import Counter

OUT = sys.argv[1] if len(sys.argv) > 1 else "out"
HERE = os.path.dirname(os.path.abspath(__file__))
Y0, Y1 = 1500, 1930
NY = Y1 - Y0 + 1
N = NY * 12 * 31

def idx(y, m, d): return ((y - Y0) * 12 + (m - 1)) * 31 + (d - 1)
def triple(i):
    d = i % 31 + 1; i //= 31
    return Y0 + i // 12, i % 12 + 1, d
def iso(i): return "%04d-%02d-%02d" % triple(i)

# ---------------------------------------------------------------- the readers
READERS = [
 ("python-date",            "Python 3.11.15",   "datetime.date(y, m, d)",            True,  "proleptic Gregorian"),
 ("sqlite-julianday",       "SQLite 3.45.1",    "julianday('y-mm-dd')",              True,  "proleptic Gregorian"),
 ("ruby-default-italy",     "Ruby 3.3.6",       "Date.new(y, m, d)",                 True,  "Julian to 1582-10-04, then Gregorian"),
 ("ruby-england",           "Ruby 3.3.6",       "Date.new(y, m, d, Date::ENGLAND)",  False, "Julian to 1752-09-02, then Gregorian"),
 ("ruby-julian",            "Ruby 3.3.6",       "Date.new(y, m, d, Date::JULIAN)",   False, "proleptic Julian"),
 ("ruby-gregorian",         "Ruby 3.3.6",       "Date.new(y, m, d, Date::GREGORIAN)",False, "proleptic Gregorian"),
 ("java-localdate",         "Java 21.0.10",     "LocalDate.of(y, m, d)",             True,  "proleptic ISO"),
 ("java-gregoriancalendar", "Java 21.0.10",     "new GregorianCalendar(); set(...)", True,  "Julian to 1582-10-04, then Gregorian"),
 ("java-gregcal-strict",    "Java 21.0.10",     "the same, setLenient(false)",       False, "Julian to 1582-10-04, then Gregorian"),
 ("js-date",                "Node 22.22.2",     "new Date(y, m-1, d)",               True,  "proleptic Gregorian"),
 ("php-checkdate",          "PHP 8.4.19",       "checkdate(m, d, y)",                True,  "proleptic Gregorian"),
 ("php-mktime",             "PHP 8.4.19",       "mktime(12, 0, 0, m, d, y)",         True,  "proleptic Gregorian"),
 ("php-juliantojd",         "PHP 8.4.19",       "juliantojd(m, d, y)",               False, "proleptic Julian"),
 ("c-timegm",               "glibc, gcc 13.3.0","timegm(&tm)",                       True,  "proleptic Gregorian"),
 ("perl-timegm",            "Perl 5.38.2",      "Time::Local::timegm_modern(...)",   True,  "proleptic Gregorian"),
 ("gnu-date",               "coreutils 9.4",    "date -f",                           True,  "proleptic Gregorian"),
]
IDS      = [r[0] for r in READERS]
DEFAULTS = [r[0] for r in READERS if r[3]]
NAMED    = [r[0] for r in READERS if not r[3]]

cols, digests = {}, {}
for rid in IDS:
    raw = open(os.path.join(OUT, rid + ".txt"), "rb").read()
    digests[rid] = hashlib.sha256(raw).hexdigest()
    lines = raw.decode().split("\n")
    if lines and lines[-1] == "": lines.pop()
    if len(lines) != N: raise SystemExit("%s: %d lines, expected %d" % (rid, len(lines), N))
    cols[rid] = [None if x == "-" else int(x) for x in lines]

# ------------------------------------------------- what each reader does alone
taken = {}          # rid -> set of indices whose day another written date also names
per = {}
for rid, lang, call, dflt, cal in READERS:
    c = cols[rid]
    seen = Counter(v for v in c if v is not None)
    taken[rid] = set(i for i, v in enumerate(c) if v is not None and seen[v] > 1)
    refused = [i for i, v in enumerate(c) if v is None]
    runs, cur = [], []
    for i in refused:
        if cur and i == cur[-1] + 1: cur.append(i)
        else:
            if cur: runs.append(cur)
            cur = [i]
    if cur: runs.append(cur)
    # a run of refusals that is not simply the end of a short month
    reform = [r for r in runs if not all(triple(i)[2] >= 29 for i in r)]
    per[rid] = {
        "language": lang, "call": call, "is_default": dflt, "calendar": cal,
        "accepted": N - len(refused), "refused": len(refused),
        "distinct_days": len(seen),
        "answers_a_day_already_named": len(taken[rid]),
        "reform_read_off_its_own_answers": [
            {"from": iso(r[0]), "to": iso(r[-1]), "days": len(r)} for r in reform],
        "sha256_of_its_answers": digests[rid],
    }

# ------------------------------------------------------ what they do together
def state(group):
    """per written date: (n_accepting, n_distinct_days_meant)"""
    acc = [0] * N; dis = [0] * N
    for i in range(N):
        vs = [cols[r][i] for r in group]
        a = [v for v in vs if v is not None]
        acc[i] = len(a); dis[i] = len(set(a))
    return acc, dis

acc_d, dis_d = state(DEFAULTS)
acc_a, dis_a = state(IDS)

L_exist  = [i for i in range(N) if 0 < acc_d[i] < len(DEFAULTS)]
L_ident  = [i for i in range(N) if dis_d[i] > 1]
L_ident16= [i for i in range(N) if dis_a[i] > 1]
refused_by_all = [i for i in range(N) if acc_a[i] == 0]
unanimous_d = sum(1 for i in range(N) if acc_d[i] == len(DEFAULTS) and dis_d[i] == 1)

# the written dates whose contested existence a calendar reform explains, as
# against the ones where the readers merely differ on strictness
REFORM_DATES = ([idx(1582,10,d) for d in range(5,15)] +
                [idx(1752,9,d)  for d in range(3,14)] +
                [idx(y,2,29)    for y in (1500,1700,1800,1900)])
ex = set(L_exist)
reform_contested = sorted(ex & set(REFORM_DATES))
strict_contested = sorted(ex - set(REFORM_DATES))
by_slot = Counter((triple(i)[1], triple(i)[2]) for i in strict_contested)

# the identity-contested span, read off the answers and not off any documentation
span = (iso(L_ident[0]), iso(L_ident[-1])) if L_ident else None
span_is_closed = bool(L_ident) and L_ident[-1] - L_ident[0] + 1 == len(L_ident)

# ------------------------------------------------------------------- counts
counts = {
  "what_was_asked": {
    "written_dates": N, "from": "1500-01-01", "to": "1930-12-31",
    "rule": "every year 1500..1930, every month 1..12, every day 1..31",
    "readers": len(IDS),
    "readers_you_get_without_asking": len(DEFAULTS),
    "readers_you_must_name": len(NAMED),
    "yardstick": "Julian Day Number, an integer naming one day of the world with no calendar in it",
  },
  "the_loud_disagreement": {
    "written_dates_some_reader_refuses_and_another_accepts_defaults": len(L_exist),
    "of_those_a_calendar_reform_explains": len(reform_contested),
    "which_are": [iso(i) for i in reform_contested],
    "the_rest_are_strictness_not_history": len(strict_contested),
    "the_rest_by_slot": {"%02d-%02d" % k: v for k, v in sorted(by_slot.items())},
  },
  "the_silent_disagreement": {
    "written_dates_every_default_accepts_and_they_do_not_all_mean_one_day": len(L_ident),
    "share_of_the_range": round(100.0 * len(L_ident) / N, 2),
    "span": span, "span_is_every_written_date_in_it": span_is_closed,
    "none_of_them_raises_an_error_anywhere": all(acc_d[i] == len(DEFAULTS) or i in ex for i in L_ident),
  },
  "the_whole_bench": {
    "written_dates_all_sixteen_agree_exist_and_mean_one_day": sum(
        1 for i in range(N) if acc_a[i] == len(IDS) and dis_a[i] == 1),
    "written_dates_contested_in_identity_among_all_sixteen": len(L_ident16),
    "written_dates_no_reader_at_all_accepts": len(refused_by_all),
    "written_dates_every_default_accepts_and_all_mean_one_day": unanimous_d,
    "share": round(100.0 * unanimous_d / N, 2),
  },
  "refuses_nothing": sorted(r for r in IDS if per[r]["refused"] == 0),
  "carries_the_cutover_of_1582_among_the_defaults": sorted(
      r for r in DEFAULTS if cols[r][idx(1582,10,4)] != cols["python-date"][idx(1582,10,4)]),
  "refuses_the_eleven_days_of_the_act": sorted(
      r for r in IDS if cols[r][idx(1752,9,3)] is None),
  "refuses_any_day_of_february_1918": sorted(
      r for r in IDS if any(cols[r][idx(1918,2,d)] is None for d in range(1,14))),
  "per_reader": per,
}

# a written date the machine cannot hold, and what it does instead
for label, i in (("1712-02-30", idx(1712,2,30)), ("1700-02-29", idx(1700,2,29))):
    counts.setdefault("two_written_dates_in_detail", {})[label] = {
        "refused_by": sorted(r for r in IDS if cols[r][i] is None),
        "accepted_by": sorted(r for r in IDS if cols[r][i] is not None),
        "and_of_those_how_many_hand_back_a_day_already_named":
            sum(1 for r in IDS if i in taken[r]),
    }

# java's lenient hybrid answers the ten deleted days with the ten that followed
i5, i15 = idx(1582,10,5), idx(1582,10,15)
counts["the_collapse"] = {
    "reader": "java-gregoriancalendar",
    "1582-10-05_is_answered_with": cols["java-gregoriancalendar"][i5],
    "1582-10-15_is_answered_with": cols["java-gregoriancalendar"][i15],
    "same_day": cols["java-gregoriancalendar"][i5] == cols["java-gregoriancalendar"][i15],
    "note": "ten written dates and the ten that follow them name ten days between them",
}

# ----------------------------------------------------------- what the page draws
def column_runs(members):
    """A layer, encoded by column: for each of the 372 slots, the runs of years
    in which that slot is contested. [slot, row0, length]"""
    s = set(members); out = []
    for slot in range(372):
        m, d = slot // 31 + 1, slot % 31 + 1
        run0, runlen = None, 0
        for row in range(NY):
            hit = idx(Y0 + row, m, d) in s
            if hit and run0 is None: run0, runlen = row, 1
            elif hit: runlen += 1
            elif run0 is not None:
                out.append([slot, run0, runlen]); run0, runlen = None, 0
        if run0 is not None: out.append([slot, run0, runlen])
    return out

WINDOWS = [
  {"key": "rome",      "title": "Rome, October 1582",
   "note": "The ten days the bull of 1582 struck out of the calendar of the Catholic states.",
   "from": idx(1582,9,26), "to": idx(1582,10,25)},
  {"key": "london",    "title": "London, September 1752",
   "note": "The eleven nominal days the Act of 1750 omitted — in Britain and its dominions, and nowhere else.",
   "from": idx(1752,8,28), "to": idx(1752,9,20)},
  {"key": "petrograd", "title": "Petrograd, February 1918",
   "note": "The thirteen days reported struck out when Russia changed its calendar.",
   "from": idx(1918,1,28), "to": idx(1918,2,18)},
]
for w in WINDOWS:
    days = [i for i in range(w["from"], w["to"] + 1) if triple(i)[2] <= 31]
    # keep only written dates that are a real slot of that month in at least one reader
    w["days"] = [iso(i) for i in days]
    w["rows"] = {}
    for rid in IDS:
        cells = []
        for i in days:
            v = cols[rid][i]
            cells.append(0 if v is None else (2 if i in taken[rid] else 1))
        w["rows"][rid] = {"cells": cells,
                          "first_day_meant": cols[rid][days[0]]}
    w.pop("from"); w.pop("to")

data = {
  "work": "NO SUCH DAY", "practice": "Ensemble, The Studio", "date": "2026-09-20",
  "grid": {"year_from": Y0, "year_to": Y1, "years": NY, "slots": 372,
           "months": 12, "days_per_month_slot": 31, "written_dates": N},
  "readers": [{"id": r[0], "language": r[1], "call": r[2], "is_default": r[3],
               "calendar": r[4],
               "accepted": per[r[0]]["accepted"], "refused": per[r[0]]["refused"],
               "already_named": per[r[0]]["answers_a_day_already_named"],
               "reform": per[r[0]]["reform_read_off_its_own_answers"]} for r in READERS],
  "layers": {
    "exist_defaults":  {"cells": len(L_exist),   "runs": column_runs(L_exist)},
    "exist_reform":    {"cells": len(reform_contested), "runs": column_runs(reform_contested)},
    "ident_defaults":  {"cells": len(L_ident),   "runs": column_runs(L_ident)},
    "ident_all":       {"cells": len(L_ident16), "runs": column_runs(L_ident16)},
  },
  "windows": WINDOWS,
  "headline": {
    "written_dates": N,
    "readers": len(IDS), "defaults": len(DEFAULTS), "named": len(NAMED),
    "loud": len(L_exist), "loud_reform": len(reform_contested),
    "silent": len(L_ident), "silent_share": round(100.0*len(L_ident)/N, 1),
    "silent_span": span,
    "refused_by_all": len(refused_by_all),
    "unanimous_defaults": unanimous_d,
    "all_sixteen_agree": counts["the_whole_bench"]["written_dates_all_sixteen_agree_exist_and_mean_one_day"],
    "refuse_nothing": len(counts["refuses_nothing"]),
    "carry_1582": len(counts["carries_the_cutover_of_1582_among_the_defaults"]),
    "refuse_1752": len(counts["refuses_the_eleven_days_of_the_act"]),
    "refuse_1918": len(counts["refuses_any_day_of_february_1918"]),
  },
}

json.dump(counts, open(os.path.join(HERE, "counts.json"), "w"), indent=1, ensure_ascii=False)
DATA_TXT = json.dumps(data, separators=(",", ":"), ensure_ascii=False)
open(os.path.join(HERE, "data.json"), "w").write(DATA_TXT)
print("counts.json + data.json written; data.json is %.0f kB" % (len(DATA_TXT)/1024))
for k, v in data["headline"].items(): print("   %-22s %s" % (k, v))

# =============================================================== the drawing
CW, CH, GAP = 2, 2, 5                      # cell width, cell height, month gap
ML, MT, MR, MB = 52, 30, 14, 18            # margins
SW = 372 * CW + 11 * GAP                   # sheet width
SH = NY * CH                               # sheet height
MONTH = ["JAN","FEB","MAR","APR","MAY","JUN","JUL","AUG","SEP","OCT","NOV","DEC"]

def sx(slot):  return ML + (slot // 31) * (31 * CW + GAP) + (slot % 31) * CW
def sy(row):   return MT + row * CH

def rects(runs, cls):
    out = []
    for slot, row0, length in runs:
        out.append('<rect x="%d" y="%d" width="%d" height="%d"/>' %
                   (sx(slot), sy(row0), CW, length * CH))
    return '<g class="%s">%s</g>' % (cls, "".join(out))

def sheet_frame():
    p = ['<rect class="sheet" x="%d" y="%d" width="%d" height="%d"/>' % (ML, MT, SW, SH)]
    for m in range(12):
        x = ML + m * (31 * CW + GAP)
        p.append('<text class="mon" x="%d" y="%d">%s</text>' % (x, MT - 10, MONTH[m]))
    for y in list(range(1500, 1931, 50)) + [1930]:
        row = y - Y0
        p.append('<text class="yr" x="%d" y="%d">%d</text>' % (ML - 8, sy(row) + 4, y))
        p.append('<line class="tick" x1="%d" y1="%d" x2="%d" y2="%d"/>' %
                 (ML - 5, sy(row), ML - 1, sy(row)))
    for y, lab in ((1582, "1582"), (1752, "1752")):
        row = y - Y0
        p.append('<line class="mark" x1="%d" y1="%d" x2="%d" y2="%d"/>' %
                 (ML - 5, sy(row) + 1, ML + SW + 5, sy(row) + 1))
        p.append('<text class="yrm" x="%d" y="%d">%s</text>' % (ML + SW + 8, sy(row) + 4, lab))
    return "".join(p)

def sheet(layer_key, extra=""):
    L = data["layers"][layer_key]
    return ('<svg viewBox="0 0 %d %d" role="img" aria-label="%s">%s%s%s</svg>'
            % (ML + SW + MR + 28, MT + SH + MB, layer_key, sheet_frame(),
               rects(L["runs"], "ink"), extra))

REFORM_MARK = (rects(data["layers"]["exist_reform"]["runs"], "red") +
  '<g class="lead">'
  '<line x1="%d" y1="%d" x2="%d" y2="%d"/><text x="%d" y="%d">the ten days of 1582</text>'
  '</g>' % (sx(9*31+4) + 12, sy(1582-Y0) + 1, sx(9*31+4) + 74, sy(1582-Y0) - 40,
            sx(9*31+4) + 76, sy(1582-Y0) - 43) +
  '<g class="lead">'
  '<line x1="%d" y1="%d" x2="%d" y2="%d"/><text x="%d" y="%d">29 February, four times in 431 years</text>'
  '</g>' % (sx(31+28) - 4, sy(1700-Y0) + 1, sx(31+28) - 30, sy(1700-Y0) + 54,
            sx(31+28) - 30, sy(1700-Y0) + 66))

def zoom_strip(members, ya, yb, m0, m1):
    """The same layer, three months wide and nine years tall, so that the edge
    the block ends at can be read off the drawing and not only off the caption."""
    s = set(members); cw, ch, gp = 9, 17, 7
    lw, top = 44, 34
    nm = m1 - m0 + 1
    W = lw + nm * (31 * cw + gp) + 128
    Hh = top + (yb - ya + 1) * ch + 10
    p = ['<rect class="sheet" x="%d" y="%d" width="%d" height="%d"/>'
         % (lw, top, nm * (31 * cw + gp) - gp, (yb - ya + 1) * ch)]
    for k, m in enumerate(range(m0, m1 + 1)):
        x0 = lw + k * (31 * cw + gp)
        p.append('<text class="mlab" x="%d" y="%d">%s</text>' % (x0, top - 18, MONTH[m-1]))
        for dd in (1, 5, 10, 15, 20, 25, 31):
            p.append('<text class="dnum" x="%.1f" y="%d">%d</text>'
                     % (x0 + (dd - 1) * cw + cw/2, top - 5, dd))
    for y in range(ya, yb + 1):
        yy = top + (y - ya) * ch
        p.append('<text class="yr" x="%d" y="%.1f">%d</text>' % (lw - 7, yy + ch - 5, y))
        for k, m in enumerate(range(m0, m1 + 1)):
            x0 = lw + k * (31 * cw + gp)
            for dd in range(1, 32):
                if idx(y, m, dd) in s:
                    p.append('<rect class="z" x="%.1f" y="%.1f" width="%d" height="%d"/>'
                             % (x0 + (dd - 1) * cw, yy, cw, ch - 2))
    x_edge = lw + (10 - m0) * (31 * cw + gp) + 14 * cw
    y_edge = top + (1582 - ya) * ch
    p.append('<g class="lead"><line x1="%.1f" y1="%.1f" x2="%.1f" y2="%.1f"/>'
             '<text x="%.1f" y="%.1f">14 October 1582 \u2014 read off the answers</text></g>'
             % (x_edge, y_edge + ch - 1, x_edge + 26, y_edge + ch + 22,
                x_edge + 29, y_edge + ch + 26))
    return ('<svg viewBox="0 0 %d %d" role="img" aria-label="the edge of the block">%s</svg>'
            % (W, Hh, "".join(p)))

# --------------------------------------------------------------- the windows
def window_svg(w):
    n = len(w["days"]); c, g = 15, 1.6
    lw, top = 178, 44
    W = lw + n * (c + g) + 66
    H = top + len(IDS) * (c + g) + 8
    p = []
    for j, ds in enumerate(w["days"]):
        x = lw + j * (c + g)
        dd = ds[8:10]
        p.append('<text class="dnum%s" x="%.1f" y="%d">%s</text>' %
                 (" nm" if ds[5:7] != w["days"][0][5:7] else "", x + c/2, top - 16, dd.lstrip("0")))
        if dd == "01" or j == 0:
            if dd == "01":
                p.append('<line class="msep" x1="%.1f" y1="%d" x2="%.1f" y2="%d"/>' %
                         (x - g/2, top - 12, x - g/2, H - 6))
            p.append('<text class="mlab" x="%.1f" y="%d">%s</text>' %
                     (x + 1, top - 30, MONTH[int(ds[5:7]) - 1]))
    p.append('<text class="mlab" x="%.1f" y="%d">the day it means by the first</text>'
             % (lw + n * (c + g) + 6, top - 16))
    for k, rid in enumerate(IDS):
        y = top + k * (c + g)
        row = w["rows"][rid]
        p.append('<text class="rl%s" x="%d" y="%.1f">%s</text>' %
                 ("" if per[rid]["is_default"] else " nm", lw - 8, y + c - 3.5, rid))
        for j, st in enumerate(row["cells"]):
            x = lw + j * (c + g)
            cls = ("no" if st == 0 else ("dup" if st == 2 else "yes"))
            p.append('<rect class="%s" x="%.1f" y="%.1f" width="%d" height="%d"/>' % (cls, x, y, c, c))
        p.append('<text class="jd" x="%.1f" y="%.1f">%s</text>' %
                 (lw + n * (c + g) + 6, y + c - 3.5,
                  row["first_day_meant"] if row["first_day_meant"] else "—"))
    return '<svg viewBox="0 0 %d %d" role="img" aria-label="%s">%s</svg>' % (W, H, w["title"], "".join(p))

# ================================================================== the page
H = data["headline"]
def n(x): return format(x, ",").replace(",", " ")

READER_ROWS = "".join(
  '<tr class="%s"><td class="mono">%s</td><td>%s</td><td class="mono sm">%s</td>'
  '<td class="num">%s</td><td class="num">%s</td><td class="num">%s</td>'
  '<td class="sm">%s</td></tr>' % (
    "" if r[3] else "nm", r[0], r[1], r[2],
    n(per[r[0]]["accepted"]), n(per[r[0]]["refused"]),
    n(per[r[0]]["answers_a_day_already_named"]),
    "; ".join("%s to %s" % (x["from"], x["to"])
              for x in per[r[0]]["reform_read_off_its_own_answers"]) or "—")
  for r in READERS)

WINDOW_BLOCKS = "".join(
  '<figure class="win"><figcaption class="wt"><strong>%s</strong> %s</figcaption>'
  '<div class="frame">%s</div></figure>' % (w["title"], w["note"], window_svg(w))
  for w in WINDOWS)

CSS = """
:root{--paper:#f2efe7;--ink:#1d1c19;--soft:#6d6759;--rule:#cfc9b8;--panel:#ebe7db;
--sheet:#e7e3d5;--red:#a33718;--mid:#7d7666;--warn:#8a6a1f}
*{box-sizing:border-box}
html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--paper);color:var(--ink);
font:16px/1.55 "Iowan Old Style",Palatino,"Palatino Linotype","Book Antiqua",Georgia,serif}
header{max-width:1000px;margin:0 auto;padding:54px 20px 4px}
main{max-width:1000px;margin:0 auto;padding:0 20px 110px}
h1{font-size:clamp(36px,8vw,82px);line-height:.94;margin:0;letter-spacing:-.025em;font-weight:600}
.dek{font-size:clamp(16px,2.3vw,20px);color:var(--soft);margin:14px 0 0;max-width:44em}
.lede{font-size:clamp(17px,2.4vw,21px);line-height:1.46;margin:30px 0 0;max-width:37em}
h2{font-size:12.5px;letter-spacing:.18em;text-transform:uppercase;font-weight:700;
margin:64px 0 6px;color:var(--soft);font-family:ui-monospace,"SFMono-Regular",Menlo,Consolas,monospace}
h3{font-size:15.5px;margin:26px 0 2px;font-weight:600}
p{max-width:38em}
.cap{color:var(--soft);font-size:14.5px;max-width:46em;margin:10px 0 0}
blockquote{margin:18px 0 0;padding:0 0 0 18px;border-left:3px solid var(--rule);
max-width:38em;font-size:17px;color:var(--ink)}
blockquote cite{display:block;font-style:normal;font-size:13.5px;color:var(--soft);margin-top:8px}
a{color:inherit;text-decoration-color:var(--rule);text-underline-offset:2px}
figure{margin:20px 0 0}
svg{display:block;width:100%;height:auto}
.frame{background:var(--panel);border:1px solid var(--rule);padding:10px;overflow-x:auto}
.sheet{fill:var(--sheet)}
.ink rect{fill:var(--ink)}
.z{fill:var(--ink)}
.red rect{fill:var(--red)}
text{font-family:ui-monospace,"SFMono-Regular",Menlo,Consolas,monospace}
.mon{font-size:9px;fill:var(--soft);letter-spacing:.08em}
.yr{font-size:9px;fill:var(--soft);text-anchor:end}
.yrm{font-size:9px;fill:var(--red)}
.tick{stroke:var(--soft);stroke-width:1}
.mark{stroke:var(--red);stroke-width:.7;opacity:.55}
.lead line{stroke:var(--red);stroke-width:.8}
.lead text{font-size:9.5px;fill:var(--red)}
.no{fill:none;stroke:var(--soft);stroke-width:.9}
.yes{fill:var(--ink)}
.dup{fill:var(--red)}
.dnum{font-size:8.5px;fill:var(--soft);text-anchor:middle}
.dnum.nm{fill:var(--ink)}
.mlab{font-size:9px;fill:var(--ink);letter-spacing:.1em}
.msep{stroke:var(--soft);stroke-width:.8;opacity:.5}
.rl{font-size:10px;fill:var(--ink);text-anchor:end}
.rl.nm{fill:var(--soft)}
.jd{font-size:9px;fill:var(--soft)}
table{border-collapse:collapse;margin:16px 0 0;font-size:13.5px;width:100%}
th,td{text-align:left;padding:4px 9px 4px 0;border-bottom:1px solid var(--rule);vertical-align:top}
th{font-size:11px;letter-spacing:.09em;text-transform:uppercase;color:var(--soft);font-weight:700;
font-family:ui-monospace,Menlo,Consolas,monospace}
td.num{text-align:right;font-variant-numeric:tabular-nums;font-family:ui-monospace,Menlo,Consolas,monospace}
.mono{font-family:ui-monospace,Menlo,Consolas,monospace}
.sm{font-size:12px;color:var(--soft)}
tr.nm td{color:var(--soft)}
tr.nm td.mono::after{content:" \\00b7 named";color:var(--soft);font-size:10px}
.big{font-size:clamp(22px,3.2vw,30px);line-height:1.22;max-width:28em;margin:34px 0 0;font-weight:600}
.big span{color:var(--red)}
ol.find{max-width:38em;padding-left:1.1em}
ol.find li{margin:16px 0 0}
.key{display:flex;flex-wrap:wrap;gap:16px;margin:12px 0 0;font-size:13px;color:var(--soft);
font-family:ui-monospace,Menlo,Consolas,monospace}
.key i{display:inline-block;width:11px;height:11px;margin-right:5px;vertical-align:-1px;font-style:normal}
.k1{background:var(--ink)}.k2{background:var(--red)}
.k3{border:1px solid var(--soft);background:none}
.win{margin-top:30px}
.wt{font-size:14px;color:var(--soft);margin-bottom:8px;max-width:46em}
.wt strong{color:var(--ink)}
/* the hand: three layers of one sheet, chosen with CSS alone */
.layers>input{position:absolute;opacity:0;pointer-events:none}
.ctl{display:flex;flex-wrap:wrap;gap:8px;margin:0 0 10px}
.ctl label{font-family:ui-monospace,Menlo,Consolas,monospace;font-size:12px;letter-spacing:.04em;
border:1px solid var(--rule);background:var(--panel);padding:7px 11px;cursor:pointer;color:var(--soft)}
#L1:checked~.ctl label[for=L1],#L2:checked~.ctl label[for=L2],#L3:checked~.ctl label[for=L3]
{background:#dcd7c6;color:var(--ink);border-color:#8d8570}
.pane{display:none}
#L1:checked~.panes .p1,#L2:checked~.panes .p2,#L3:checked~.panes .p3{display:block}
.pane .cap{margin-top:12px}
@media (max-width:640px){.frame{padding:6px}}
"""

PAGE = """<!DOCTYPE html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>NO SUCH DAY — Ensemble</title>
<meta name="description" content="Sixteen date implementations on one machine, asked about every written date from 1500 to 1930. The days two calendar reforms deleted are still refused by a few of them, and 30 797 written dates are accepted by all of them and mean two different things.">
<style>%(css)s</style></head>
<body>
<header>
<h1>NO SUCH DAY</h1>
<p class="dek">Ensemble · The Studio · 2026-09-20 · a census of sixteen calendars found on one machine</p>
<p class="lede">In 1752 an Act of the Parliament of Great Britain struck eleven days out of the
calendar, and was careful to say that what it struck out were their names: the natural day after the
second of September was to be <em>called</em> the fourteenth. The day itself it left alone. Two hundred and seventy-four years later
this machine holds sixteen ways of writing a date down. Each was asked tonight about every written date
from 1500 to 1930 — %(N)s of them — and about which day of the world it meant.
<strong>Six refuse nothing at all.</strong> Two of the eleven you get without asking still keep the
deletion Rome ordered in 1582. Not one of the eleven keeps London’s. And on %(silent)s written dates
— every single one from 1 January 1500 to 14 October 1582 — all eleven accept, none complains, and
they do not all mean the same day.</p>
</header>
<main>

<h2>1 · The Act says what it is deleting</h2>
<p>The Calendar (New Style) Act 1750 is a public general Act of the Parliament of Great Britain, and its
operative sentence is still published word for word by the United Kingdom’s statute service. It does
not say that eleven days did not happen. It says what is to be done with their names.</p>
<blockquote>… the natural day next immediately following the said second day of September shall be
called, reckoned, and accounted to be the fourteenth day of September, <strong>omitting for that time only
the eleven intermediate nominal days of the common calendar</strong> …
<cite>Calendar (New Style) Act 1750 (24 Geo. 2 c. 23), section 1 — <a href="https://www.legislation.gov.uk/apgb/Geo2/24/23/section/1.">legislation.gov.uk</a>, read 2026-09-20</cite></blockquote>
<p><strong>Nominal.</strong> A numbering was struck out; the natural day next immediately following went on as
it was. And the Act’s own preamble settles where those eleven numbers had gone: the corrected calendar,
it says, <em>“hath been received and established, and is now generally practised by almost all other
nations of Europe”</em>. On the third of September 1752 the third of September was an ordinary working
date across the Channel. The Act did not make a hole in time. It made a hole in one jurisdiction’s
paperwork — and it is that hole, not the days, that the software of 2026 has inherited.</p>

<h2>2 · The question, and who was asked</h2>
<p>Every year from 1500 to 1930, every month, every day from 1 to 31: <strong>%(N)s written dates</strong>,
in one fixed order. Sixteen implementations that happened to be installed on this machine were each
handed the whole list and asked two things in one answer — <em>do you accept this written date</em>, and
if so <em>which day do you mean by it</em>. The answer is a Julian Day Number: an integer that names one
day of the world and carries no calendar inside it. Eleven of the sixteen are what a person gets by doing
the obvious thing in that language. Five have to be asked for by name, and are marked so below.</p>
<p><strong>Nothing in this census is a defect, and nothing here is an accusation.</strong> Every behaviour
below is documented by the implementation that has it, and most of them are documented as the correct
thing to do. The question is not whether any of them is wrong. It is what a person who writes a date
down and does not choose gets handed instead.</p>
<div class="frame" style="padding:0;border:0;background:none">
<table><thead><tr><th>reader</th><th>where it lives</th><th>the call</th><th>accepts</th><th>refuses</th>
<th>hands back a day another written date also names</th>
<th>the reform legible in its own answers</th></tr></thead>
<tbody>%(rows)s</tbody></table></div>
<p class="cap">Five rows are greyed: those are the calendars you only get if you name them. The last
column was not read out of any manual. It is the unbroken run of refusals each reader produces that is
not simply the end of a short month — the reform read back out of the answers, the way a survey’s
exclusion rule can be read back out of its entries.</p>

<h2>3 · Where the machine does not agree with itself</h2>
<p>One sheet, one cell for every written date: 431 years down, twelve months of 31 slots across. There is
ink <strong>only where the eleven defaults disagree</strong>. Blank paper is agreement. Three questions can
be put to the same sheet, and the answers are not the same size.</p>
<div class="layers">
<input type="radio" name="L" id="L1" checked><input type="radio" name="L" id="L2"><input type="radio" name="L" id="L3">
<div class="ctl">
<label for="L1">does the day exist · 11 defaults</label>
<label for="L2">do they mean one day · 11 defaults</label>
<label for="L3">do they mean one day · all 16</label>
</div>
<div class="panes">
<div class="pane p1"><div class="frame">%(sheet1)s</div>
<div class="key"><span><i class="k1"></i>one default refuses it, another takes it — %(loud)s written dates</span>
<span><i class="k2"></i>of those, the %(loudr)s a calendar reform explains</span></div>
<p class="cap">Almost all of this is not history. Six vertical lines are 31 November, 31 September,
31 June, 31 April, 30 February and 31 February — written dates no calendar has ever had, which some
readers refuse and others quietly move. A seventh, broken line is 29 February in the 323 years that are
not leap years. Only <strong>%(loudr)s cells on the whole sheet</strong> are contested because of a calendar
reform: the ten days of October 1582, and 29 February in 1500, 1700, 1800 and 1900 — Julian leap days
that were ordinary dates in England while England was still keeping the Julian calendar.</p></div>
<div class="pane p2"><div class="frame">%(sheet2)s</div>
<figure><div class="frame">%(zoom)s</div>
<p class="cap">The last years of the block, three months wide. The edge is not a straight
line across the year: it runs to the end of September 1582, fourteen days into October, and
stops. No documentation was consulted to place it — it is where the eleven answers stop
dividing.</p></figure>
<div class="key"><span><i class="k1"></i>every default accepts it and they do not all mean the same day
— %(silent)s written dates, %(silentsh)s%% of the range</span></div>
<p class="cap">The same eleven readers, the same sheet, one question further on. The block ends at
<strong>14 October 1582</strong> and it is solid: every written date from 1 January 1500 to that day is in it,
with no exception anywhere. Nine of the eleven read those dates as if the correction of 1582 had always
been in force; two keep the calendar that was actually in use. The two readings are ten days apart, and
<strong>not one of the eleven raises so much as a warning.</strong> The loud disagreement is %(loudr)s days
and you can see it only because it is drawn in red. The silent one is %(silent)s and it is a fifth of the
page.</p></div>
<div class="pane p3"><div class="frame">%(sheet3)s</div>
<div class="key"><span><i class="k1"></i>the sixteen do not all mean one day — %(N)s written dates</span></div>
<p class="cap">Ask every calendar the machine ships, including the five you have to name, and the sheet
fills. There is <strong>no day at all between 1500 and 1930</strong> — not one of %(N)s — on which all
sixteen agree which day is meant. Two of them implement the Julian calendar and say so plainly, which is
the whole of the reason; a reader who names <span class="mono">Date::JULIAN</span> has asked for exactly
this. It is put here because the number is nought and because it shows what the previous sheet is
measuring: not confusion, but the distance between calendars that a default hides and a name declares.</p></div>
</div></div>

<h2>4 · Three windows</h2>
<p>The same answers at the scale of a single day. A filled square is a written date the reader accepts and
that no other written date shares; a red square is one it accepts and answers with a day another written
date also names; an empty square is a refusal. The number at the right of each row is the day that reader
means by the first written date in the window.</p>
<div class="key"><span><i class="k1"></i>accepted, its own day</span>
<span><i class="k2"></i>accepted, a day already named</span>
<span><i class="k3"></i>refused</span></div>
%(windows)s
<p class="cap">Read the three together. In October 1582 two readers refuse the ten days and one
— Java’s <span class="mono">GregorianCalendar</span>, constructed the ordinary way — accepts every one
of them and hands back the day that follows them: ask it for the fifth of October and you are given the
fifteenth, with no error and no flag. In September 1752 exactly one of the sixteen refuses the eleven days
of the Act, and only if you have named <span class="mono">Date::ENGLAND</span> yourself; to the other
fifteen, and to all eleven defaults, the Act never happened. In February 1918 nothing is refused by
anybody: whatever was done to the calendar in Petrograd is not in this machine at all.</p>

<h2>5 · What came out</h2>
<ol class="find">
<li><strong>The loud disagreement is small and almost never historical.</strong> %(loud)s written dates
are refused by one default and taken by another. Only %(loudr)s of them have anything to do with a
calendar reform. The other %(loudrest)s are 30 February and its kind: the difference between a reader
that refuses an impossible written date and a reader that silently moves it to a possible one.</li>
<li><strong>The silent disagreement is a fifth of the range.</strong> %(silent)s written dates that every
default accepts, that raise nothing anywhere, and that do not all name the same day. That set is exactly
1 January 1500 to 14 October 1582, boundary and all, and it was read off the answers rather than out of a
manual.</li>
<li><strong>Six of the sixteen refuse nothing whatever.</strong> SQLite, Java’s GregorianCalendar,
JavaScript’s Date, PHP’s mktime, PHP’s Julian converter and the C library’s timegm accept all %(N)s
written dates, and each answers between 5 818 and 5 844 of them with a day another written date has
already claimed. A record that says 30 February does not fail on the way in. It becomes the first of
March, and nothing downstream can tell.</li>
<li><strong>The machine remembers one jurisdiction.</strong> Rome’s deletion of 1582 is kept by two of the
eleven defaults. London’s deletion of 1752 is kept by one reader out of sixteen, and only when a person
names it. For Sweden’s 30 February 1712 there is no setting at all: ten readers refuse it, and the six
that take it are exactly the six that refuse nothing — each of them files it under a day that already has
a name. Of February 1918, nothing. The default calendar
of this machine is a Catholic administrative act of 1582, and every other jurisdiction’s is a
configuration option or absent.</li>
<li><strong>Not one written date in 431 years is impossible everywhere.</strong> %(refall)s of %(N)s are
refused by all sixteen. There is no such thing, on this machine, as a date that does not exist — only
dates that some readers will not take.</li>
<li><strong>A deletion of names is stored as a deletion of days.</strong> This is the whole finding, and
the Act of 1750 is the witness against the software: it omitted eleven <em>nominal</em> days and said so in
that word. The readers that keep a reform keep it by refusing the date or by moving it, which are both
ways of saying the day was not there. None of the sixteen has any way to say what actually happened —
that the day was there and its name was somewhere else.</li>
</ol>
<p class="big">The eleven days were not missing. <span>Their numbers were.</span> Every reader on this
machine stores the second thing as if it were the first.</p>

<h2>6 · What this does not say</h2>
<p><strong>No implementation is criticised here and none is wrong.</strong> A proleptic calendar — running
today’s rule backwards through dates nobody kept it on — is the right choice for most work, and the
libraries that make it say so in their documentation. Ruby’s <span class="mono">Date</span> takes the
reform date as an argument and ships three named alternatives; Java ships two clocks and supports both.
This page counts answers; it does not grade them.</p>
<p><strong>What is a primary source here and what is not.</strong> The Act of 1750 was read tonight at the
United Kingdom’s own statute service and is quoted from it. The census is this practice’s own
measurement, reproducible from the scripts beside this page. Everything else about the other reforms —
that Rome’s bull of 1582 struck ten days, that Sweden kept a 30 February in 1712, that Russia’s change
in 1918 struck thirteen — is taken from secondary literature, is marked as such wherever it appears,
and was <strong>not</strong> verified against an original document by this practice. Nothing measured here
depends on those three claims: the readers’ answers about those dates are facts about the readers.</p>
<p><strong>Sixteen is what this machine had.</strong> Not a sample of anything. A different machine would
hold a different sixteen, and the shares on this page would move; the one number that would not is the
count of jurisdictions the defaults remember, which is one.</p>

<h2>7 · Nearest works, and the daylight</h2>
<p>Four works of the house’s Atlas of Data Art, each opened at its own address on 2026-09-20 before this
one was built, and what stands between them and this page.</p>
<h3>Kate Crawford &amp; Vladan Joler, <em>Calculating Empires: A Genealogy of Technology and Power,
1500–2025</em> (2023–2025)</h3>
<p><a href="https://ars.electronica.art/starts-prize/en/calculating-empires/">At the prize page</a>:
photographs of a hand-drawn diptych over twenty-four metres long and three high, five centuries of
communication devices on one side and of control and classification on the other, with two handmade
volumes a visitor is invited to annotate. <strong>Daylight:</strong> their five centuries start in 1500 too,
and their line is continuous by design — the argument is that nothing arrived from nowhere. This sheet
covers the same five centuries and draws ink <em>only where the line breaks</em>, and it is drawn not by a
hand but by sixteen machines that were asked and answered. Their diagram is a genealogy a person
composed; this one is a census nobody composed, and its shape was not known until it was run.</p>
<h3>Trevor Paglen, <em>From ‘Apple’ to ‘Anomaly’ (Pictures and Labels)</em> (2019–2020)</h3>
<p><a href="https://www.barbican.org.uk/s/trevorpaglen/">At the Barbican’s page</a>: a text-heavy piece
with photographs of Paglen at the gallery and a long conversation with the curator, on ImageNet’s
twenty thousand categories and the judgements buried in them. <strong>Daylight:</strong> his subject is a
taxonomy that was assembled recently, by people who can be named, and whose violence is that it
mislabels human beings. The taxonomy here is a papal act of 1582 and a statute of 1750, shipped as the
default of nearly every runtime on earth, and its violence is milder and stranger: it does not mislabel a
day, it declares that the day was never there — or moves it, without a word.</p>
<h3>Brian Mackern, <em>netart_latino database</em> (1999–2005)</h3>
<p><a href="http://netart.org.uy/brian.html">At the address the Atlas cites</a> — which is the artist’s
own CV page, still loading, ASCII masthead intact, eight bracketed sections from 1995 to 2025, the
database itself described there as territorialised by national domain and reachable now mainly through
archives. <strong>Daylight:</strong> he replaced one default classification with another <em>on purpose</em>,
and the point was that somebody chose. Nobody chose the classification measured here. It is what you get
by not choosing, and it is the same in eleven languages that have nothing else in common.</p>
<h3>Tega Brain, <em>Slop Evader</em> (2026)</h3>
<p><a href="https://ars.electronica.art/starts-prize/en/slop-evader/">At the prize page</a>: screenshots
of a search tool and browser extension that returns only results published before 30 November 2022, the
day a chat interface was released to the public, described there as a small act of refusal.
<strong>Daylight:</strong> hers is a date drawn deliberately, published as the instrument, and doing
exactly what it says. The dates on this page were drawn in 1582 and 1752 by people with other business,
are published nowhere a user of a date library will see them, and cut a record in half without being
declared at all. The same mechanism — a single date deciding what is admissible — once as a stated
method and once as an inheritance.</p>
<p class="cap">Named and deliberately not answered a sixth time: Mimi Ọụnọha’s <em>The Library of
Missing Datasets</em>. Her cabinets hold absences a society chose and could choose otherwise. Nothing is
absent here — every day is present in every reader, which is exactly the trouble.</p>

<h2>8 · The machine, and how to run this again</h2>
<p>Sixteen readers, on one machine, on 2026-09-20: %(versions)s. The scripts that put the question are in
<span class="mono">census/</span>, one per language, and <span class="mono">build.py</span> derives every
figure on this page and draws it.
<span class="mono">counts.json</span> holds all of them, including the ones that are not printed here.
The sixteen answer files are 160 332 lines each and are <strong>not</strong> committed: they are
regenerated in a few seconds, and the SHA-256 of every one of them is in
<span class="mono">counts.json</span> so that a later run can be compared with this one.</p>
<p class="cap">Work CC BY 4.0, code Apache-2.0. No third-party code is embedded and no library is loaded;
the page makes no network request of any kind and works with scripting switched off — the three controls
on the sheet are CSS. The short quotations from the Act of 1750 are quotations from a public statute,
linked to the service that publishes it.</p>

<script type="application/json" id="data">%(data)s</script>
</main></body></html>
"""

versions = ", ".join(sorted(set("%s" % r[1] for r in READERS)))
html = PAGE % {
  "css": CSS, "rows": READER_ROWS, "windows": WINDOW_BLOCKS,
  "sheet1": sheet("exist_defaults", REFORM_MARK),
  "sheet2": sheet("ident_defaults"),
  "sheet3": sheet("ident_all"),
  "zoom": zoom_strip(L_ident, 1578, 1584, 8, 11),
  "N": n(N), "loud": n(H["loud"]), "loudr": n(H["loud_reform"]),
  "loudrest": n(H["loud"] - H["loud_reform"]),
  "silent": n(H["silent"]), "silentsh": H["silent_share"],
  "refall": n(H["refused_by_all"]), "versions": versions, "data": DATA_TXT,
}
open(os.path.join(HERE, "index.html"), "w").write(html)
print("index.html written, %.0f kB" % (len(html)/1024))
