// node verify_browser.mjs — real browser at 390 and 1100 px: opens frames, reads the figure, opens all, moves the slider, checks overflow and errors.
import { createRequire } from 'module';
const require = createRequire('/opt/node-tools/node_modules/');
const { chromium } = require('playwright');
import { dirname, join } from 'path';
const here = dirname(new URL(import.meta.url).pathname);
let ran = 0, failed = 0;
const ok = (n, c, note) => { ran++; if (!c) { failed++; console.log('  FAIL ', n, note ?? ''); } };
const browser = await chromium.launch({ args: ['--no-sandbox'] });
for (const [w, h] of [[390, 800], [1100, 900]]) {
  const page = await browser.newPage({ viewport: { width: w, height: h } });
  const errs = [], reqs = [];
  page.on('pageerror', e => errs.push(String(e)));
  page.on('request', r => { if (!r.url().startsWith('file:')) reqs.push(r.url()); });
  await page.goto('file://' + join(here, 'index.html'));
  await page.waitForFunction(() => window.__unshown);
  ok(`${w}: 1528 strip cells`, await page.locator('#strip rect').count() === 1528);
  ok(`${w}: 135 sealed cards`, await page.locator('#wall .c').count() === 135);
  ok(`${w}: none open at the start`, await page.locator('#wall .c.open').count() === 0);
  ok(`${w}: figure has bars before any opening`, await page.locator('#fig rect').count() === 5);
  ok(`${w}: sealed cards hide their note`, await page.evaluate(() => [...document.querySelectorAll('.c .note')].every(n => n.offsetParent === null)));
  await page.click('#b1');
  ok(`${w}: one opened`, await page.locator('#wall .c.open').count() === 1 && (await page.textContent('#cnt')).startsWith('1 of 135'));
  ok(`${w}: opened note visible`, await page.evaluate(() => [...document.querySelectorAll('.c.open .note')].every(n => n.offsetParent !== null)));
  await page.click('#b10');
  ok(`${w}: eleven opened`, await page.locator('#wall .c.open').count() === 11);
  ok(`${w}: bound shown`, /%/.test(await page.textContent('#n-bound')));
  ok(`${w}: odd count 0`, (await page.textContent('#n-odd')) === '0');
  ok(`${w}: joined hidden until all open`, await page.evaluate(() => getComputedStyle(document.getElementById('joined')).display === 'none'));
  await page.locator('#wall .c:not(.open)').first().click();
  ok(`${w}: click opens a card`, await page.locator('#wall .c.open').count() === 12);
  await page.click('#ball');
  ok(`${w}: all opened`, await page.locator('#wall .c.open').count() === 135);
  ok(`${w}: green cells in strip`, await page.evaluate(() => [...document.querySelectorAll('#strip rect')].filter(r => r.getAttribute('fill') === '#7fb069').length === 135));
  ok(`${w}: joined shown`, await page.evaluate(() => getComputedStyle(document.getElementById('joined')).display === 'block'));
  ok(`${w}: bound after all = 2.8 %`, /^2\.8 %/.test(await page.textContent('#n-bound')), await page.textContent('#n-bound'));
  ok(`${w}: joined share 0.33 %`, (await page.textContent('#j-share')) === '0.33 %');
  await page.evaluate(() => { const r = document.getElementById('rate'); r.value = 2; r.dispatchEvent(new Event('input')); });
  ok(`${w}: slider moves the count`, /25 more odd frames/.test(await page.textContent('#rate-out')), await page.textContent('#rate-out'));
  ok(`${w}: hard frames carry the amber edge`, await page.locator('#wall .c.hard').count() === 3);
  await page.click('#breset');
  ok(`${w}: reset seals`, await page.locator('#wall .c.open').count() === 0 && (await page.textContent('#cnt')).startsWith('0 of 135'));
  ok(`${w}: no sideways overflow`, await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1));
  ok(`${w}: no network request`, reqs.length === 0, reqs.join(','));
  ok(`${w}: no page errors`, errs.length === 0, errs.join(';'));
  await page.click('#ball');
  await page.evaluate(() => document.getElementById('wall').scrollIntoView());
  await page.screenshot({ path: join(here, `shot-${w}.png`), fullPage: false });
  await page.close();
}
await browser.close();
console.log(`${ran - failed} passed, ${failed} failed`);
process.exit(failed ? 1 : 0);
