"""NEVER HUNG — the hand-authored part of the work.

Everything in this file is a judgment: which works this practice decided not to make,
which documents in this repository belong to each of them, and which sentence of the
record is the one that killed it. Nothing here is a measurement. Every number on the
page is computed from these paths by build.py, and every quoted sentence is checked
against the file it is attributed to before the page is written.

Assignment rule, applied throughout and stated on the page:
  - A work's RECORD is the documents dedicated to it: its project directory, its named
    ruling and proposal documents, and its entry in memory/discarded.md.
  - Session minutes are NOT counted. A journal file is the minutes of a whole evening
    and usually holds several pieces of business; it is cited beside each work as
    evidence and never measured.
  - No file is assigned to two works.
"""

# The register this practice keeps of its own refusals.
REGISTER = "memory/discarded.md"

# kinds
CONCEPT = "killed at concept"
AFTER_BUILD = "killed after it was built"
DIRECTION = "refused as a direction"
RETURNED = "killed, then made"
HELD = "never refused, never shown"

WORKS = [
    dict(
        n=1, title="Ledger of Days", date="2026-07-12", session=1, kind=CONCEPT,
        gloss="A durational, sonic marking of the laboratory's whole archive of records: one sound per document, the archive read as time.",
        quote="sonifying/ritualizing records with no claim attached is wallpaper by definition",
        quote_src=REGISTER,
        register_anchor='**2026-07-12 (session 01) — "Ledger of Days" REJECTED at proposal.**',
        paths=[],
        minutes=["journal/2026-07-12.md"],
    ),
    dict(
        n=2, title="Diminishing Returns", date="2026-07-12", session=5, kind=AFTER_BUILD,
        gloss="The founding project of this practice, three sessions and two increments in: the arithmetic of what large companies disclose about the cost of their machines, built as a playable page.",
        quote="a zero-context museum visitor cannot grasp it without prose; the context never became experiential",
        quote_src=REGISTER,
        register_anchor='**2026-07-12 (session 05) — "Diminishing Returns" KILLED after increment 2**',
        paths=["projects/diminishing-returns", "memory/dossiers/diminishing-returns.md"],
        minutes=["journal/2026-07-12.md"],
    ),
    dict(
        n=3, title="The Quiet Signature", date="2026-07-12", session=5, kind=CONCEPT,
        gloss="Predict-then-reveal on forensic specimens: the visitor guesses, then the record answers.",
        quote="predict-then-reveal on forensic specimens fails the terminal test and the material bar identically",
        quote_src=REGISTER,
        register_anchor='**2026-07-12 (session 05) — "The Quiet Signature" (parked since session 01) killed by the',
        paths=[],
        minutes=["journal/2026-07-12.md"],
    ),
    dict(
        n=4, title="Certified", date="2026-07-12", session=6, kind=CONCEPT,
        gloss="A booth in which a visitor mints a seal of authenticity for anything at all, and walks out with it.",
        quote="a seal-minting booth restages it as a parlor trick — no named victim, no consequence",
        quote_src=REGISTER,
        register_anchor='**2026-07-12 (session 06) — "Certified" KILLED at concept**',
        paths=[],
        minutes=["journal/2026-07-12.md"],
    ),
    dict(
        n=5, title="No Way of Knowing", date="2026-07-12", session=6, kind=RETURNED,
        gloss="A solemn room built around a single unresolvable fact — killed at concept, and readmitted five days later once there was investigative work behind the verdict.",
        quote="a vigil, not an investigation — one SNIPPET-tier fact inside a solemn room; sincerity standing in for evidence",
        quote_src=REGISTER,
        register_anchor='**2026-07-12 (session 06) — "No Way of Knowing" KILLED at concept**',
        paths=[],
        minutes=["journal/2026-07-12.md"],
        note="It came back. The work premiered on 2026-07-17 and stands at works/2026-07-17-no-way-of-knowing/. This is the only frame on the wall whose absence closed.",
    ),
    dict(
        n=6, title="The Exemption", date="2026-07-13", session=12, kind=CONCEPT,
        gloss="A sorting wall on the European AI Act, climaxing in a stamp that reads: this work is exempt.",
        quote="The artistic/satirical clause is NOT an exemption from disclosure",
        quote_src=REGISTER,
        register_anchor='## 2026-07-13 (session 12) — "The Exemption" — KILLED AT CONCEPT',
        paths=[],
        minutes=["journal/2026-07-13.md"],
    ),
    dict(
        n=7, title="Admissible", date="2026-07-13", session=12, kind=CONCEPT,
        gloss="An evidence tray holding a score a court refused to admit, handled by the visitor like a court exhibit.",
        quote="Returns only with the fact independently pinned AND a form that is not the evidence tray.",
        quote_src=REGISTER,
        register_anchor='## 2026-07-13 (session 12) — "Admissible" — KILLED AT CONCEPT',
        paths=[],
        minutes=["journal/2026-07-13.md"],
    ),
    dict(
        n=8, title="Safe", date="2026-07-17", session=18, kind=CONCEPT,
        gloss="A content-moderation console: the visitor tags fragments allow or block while a wage meter ticks at a real, sourced hourly rate, and is then thanked by the finished assistant for keeping it clean.",
        quote="the interaction contradicts its own subject",
        quote_src=REGISTER,
        register_anchor='## 2026-07-17 (session 18) — "Safe" — KILLED AT CONCEPT',
        paths=[],
        minutes=["journal/2026-07-17.md"],
    ),
    dict(
        n=9, title="One Tap", date="2026-07-25", session=43, kind=AFTER_BUILD,
        gloss="Five primary-verified figures for the water a single query costs, staged three times in three registers; premiered 2026-07-23 and withdrawn two days later.",
        quote="not one of the five figures was ever struck",
        quote_src=REGISTER,
        register_anchor='## 2026-07-25 (session 43) — "One Tap" — KILLED AFTER PREMIERE',
        paths=["memory/dossiers/one-tap.md"],
        minutes=["journal/2026-07-25-session-43.md"],
        note="The withdrawn work is kept whole at works/2026-07-23-one-tap/ — a killed work is not deleted here. Its files are not counted in this frame; the frame measures the record of the killing.",
    ),
    dict(
        n=10, title="Order List", date="2026-07-25", session=44, kind=CONCEPT,
        gloss="One real court order list rendered at four pixels, unreadable; the visitor holds a budget of three, and each one spent makes a single named petition legible for ever, leaving the rest dark by their hand.",
        quote="Illegibility manufactures the excuse, not the crime.",
        quote_src=REGISTER,
        register_anchor='## 2026-07-25 (session 44) — "ORDER LIST" — KILLED AT CONCEPT',
        paths=["etudes/5000-series/README.md", "etudes/5000-series/THE-SENTENCE.md", "etudes/5000-series/corpus"],
        minutes=["journal/2026-07-25-session-44.md"],
    ),
    dict(
        n=11, title="5001", date="2026-07-26", session=45, kind=CONCEPT,
        gloss="A wall of 792 printed cards, one per person a court refused in a single morning; the stranger is issued the next unwritten card and writes, in their own hand and over their own signature, the reason that was withheld.",
        quote="a wall of strangers' justifications does not expose the institution's omission, it discharges it",
        quote_src=REGISTER,
        register_anchor='## 2026-07-26 (session 45) — "5001" — KILLED AT CONCEPT',
        paths=["etudes/5000-series/VECTOR-2-proposal.md"],
        minutes=["journal/2026-07-26.md"],
        note="Its own ruling names Mimi Ọnụọha as the direct ancestor of the form, on the same page that kills it for filling her folders with volunteers.",
    ),
    dict(
        n=12, title="The Revisions", date="2026-07-31", session=52, kind=CONCEPT,
        gloss="A nightly byte-for-byte watch on the pages where named institutions state what their machines cost, every change kept and dated for ever — a wall of stillness in which one night a number changed and nobody was told.",
        quote="a proposal that hides its neighbours is presumed to be copying them, and this is the nearest neighbour any proposal in this house has ever had",
        quote_src=REGISTER,
        register_anchor='**2026-07-31 (session 52) — "THE REVISIONS" KILLED AT CONCEPT**',
        paths=[],
        minutes=["journal/2026-07-31-session-52.md"],
    ),
    dict(
        n=13, title="At Mass", date="2026-07-31", session=52, kind=DIRECTION,
        gloss="Not a work but a direction for a whole season: every work to stand on a corpus no person could read, asserting only what holds across the whole of it.",
        quote="A studio that mis-counted a thirty-nine-page PDF three times in five sessions now proposes to be believed about two thousand documents.",
        quote_src=REGISTER,
        register_anchor='**2026-07-31 (session 52) — "AT MASS" DECLINED as a season direction**',
        paths=[],
        minutes=["journal/2026-07-31-session-52.md"],
    ),
    dict(
        n=14, title="At Any Time", date="2026-07-31", session=55, kind=CONCEPT,
        gloss="A court's miscellaneous orders — issued, in the court's own words, in individual cases at any time — one page-height per calendar day, the sheet reproduced entire, four days in five carrying nothing at all.",
        quote="a finding a visitor cannot receive is not a finding the work makes",
        quote_src=REGISTER,
        register_anchor='## 2026-07-31 (session 55) — "AT ANY TIME" — KILLED AT CONCEPT',
        paths=["projects/at-any-time", "etudes/at-any-time"],
        minutes=["journal/2026-07-31-session-55.md"],
    ),
    dict(
        n=15, title="You Are Under a Duty", date="2026-08-02", session=57, kind=CONCEPT,
        gloss="A public register of statutory reports that were never answered — forty-nine outstanding duties, tens of thousands of days late, and a page that erases a body's lateness the moment it answers.",
        quote="Not one of the ten readers says anybody died.",
        quote_src=REGISTER,
        register_anchor='## 2026-08-02 (session 57) — "YOU ARE UNDER A DUTY" — KILLED AT CONCEPT',
        paths=["projects/pfd-channel", "etudes/you-are-under-a-duty"],
        minutes=["journal/2026-08-02.md"],
    ),
    dict(
        n=16, title="The Room", date="2026-08-02", session=60, kind=CONCEPT,
        gloss="The spatial form of a recall work: one recalled object standing whole beside its whole notice, and on the floor everything the previous objects became when their notices were obeyed.",
        quote="Literal code: 0 of 5 in both panels.",
        quote_src=REGISTER,
        register_anchor='## 2026-08-02 (session 60) — **THE ROOM** of *STOP USING IMMEDIATELY*',
        paths=["projects/cpsc-recall-channel/PANELS-60.md",
               "projects/cpsc-recall-channel/PILLORY-AUDIT-60.md",
               "projects/cpsc-recall-channel/KRITIKER-GATE-60.md",
               "projects/cpsc-recall-channel/ARTIST-SCORE-60.md",
               "projects/cpsc-recall-channel/VERIFIER-60.md"],
        minutes=["journal/2026-08-02-session-60.md"],
    ),
    dict(
        n=17, title="Stop Using Immediately", date="2026-08-03", session=62, kind=AFTER_BUILD,
        gloss="A nine-clause score, 129 words, sending a stranger to a public recall register to look up something in their own home and, if a notice names it, carry out the state's remedy — destroy your own property with your own hands, photograph it, and send the photograph to the firm that sold it, for money.",
        quote="0 of 5 on the sheet (session 61), 0 of 5 on the page (session 62)",
        quote_src=REGISTER,
        register_anchor='**2026-08-03 (session 62) — *STOP USING IMMEDIATELY* KILLED at the publication gate**',
        paths=["projects/cpsc-recall-channel/ADJACENCY-58.md",
               "projects/cpsc-recall-channel/ARTIST-AMENDMENT-61.md",
               "projects/cpsc-recall-channel/ARTIST-PROPOSAL-58.md",
               "projects/cpsc-recall-channel/ARTIST-REFORM-59.md",
               "projects/cpsc-recall-channel/ENTRANCE-TEST-59.md",
               "projects/cpsc-recall-channel/FEASIBILITY-58.md",
               "projects/cpsc-recall-channel/KRITIKER-GATE-62.md",
               "projects/cpsc-recall-channel/PANEL-61.md",
               "projects/cpsc-recall-channel/PANEL-62.md",
               "projects/cpsc-recall-channel/PANEL-PREREG-61.md",
               "projects/cpsc-recall-channel/PANEL-PREREG-62.md",
               "projects/cpsc-recall-channel/PERFORMANCE-LOG.md",
               "projects/cpsc-recall-channel/SEASON-CONDITIONS.md",
               "projects/cpsc-recall-channel/STAGING-RULING-58.md",
               "projects/cpsc-recall-channel/STAGING-RULING-59.md",
               "projects/cpsc-recall-channel/STAGING-RULING-62.md",
               "projects/cpsc-recall-channel/THE-RULE.md",
               "projects/cpsc-recall-channel/THE-SCORE.md",
               "projects/cpsc-recall-channel/VERIFIER-58.md",
               "projects/cpsc-recall-channel/VERIFIER-59.md",
               "projects/cpsc-recall-channel/VERIFIER-61.md",
               "projects/cpsc-recall-channel/VERIFIER-62-BRANDMARK.md",
               "projects/cpsc-recall-channel/VERIFIER-62-FACE.md",
               "memory/dossiers/stop-using-immediately.md"],
        minutes=["journal/2026-08-03-session-62.md"],
        note="One built page, 8,530 bytes, never promoted out of projects/cpsc-recall-channel/candidate/.",
    ),
    dict(
        n=18, title="Fifty-Nine Names", date="2026-08-04", session=64, kind=CONCEPT,
        gloss="Three minutes for one voice and one room: the emergency event codes of a federal rule read whole and in the government's order, the list stopping where no code exists, and then a false missile alert and the correction that followed it thirty-eight minutes later.",
        quote="The composition is the false claim",
        quote_src=REGISTER,
        register_anchor='## 2026-08-04 (session 64) — **"FIFTY-NINE NAMES"** — KILLED AT CONCEPT',
        paths=["projects/correction-too-late/ARTIST-64.md",
               "projects/correction-too-late/KRITIKER-GATE-64.md",
               "projects/correction-too-late/MATERIAL-64.md",
               "projects/correction-too-late/COUNT-64.md",
               "projects/correction-too-late/VERIFIER-64.md",
               "projects/correction-too-late/CONDUCTOR-VERIFICATION-64.md"],
        minutes=["journal/2026-08-04-session-64.md"],
        note="Killed the same night it was written, by a death condition its own author had published against it.",
    ),
    dict(
        n=19, title="The Sheet, the Card and the Pen", date="2026-08-04", session=65, kind=CONCEPT,
        gloss="One sheet, one card, one pen: a visitor copies out by hand a sentence a public body issued, takes the card away, turns the sheet over and finds the correction — older than the sheet, in their hand the whole time, asking them for nothing.",
        quote="Five of five would throw it away.",
        quote_src=REGISTER,
        register_anchor='## 2026-08-04 (session 65) — **THE SHEET, THE CARD AND THE PEN**',
        paths=["projects/correction-too-late/DRAMATURG-64.md",
               "projects/correction-too-late/SHEET-65.md",
               "projects/correction-too-late/PANEL-65.md",
               "projects/correction-too-late/KRITIKER-GATE-65.md",
               "projects/correction-too-late/NEIGHBOURS-65.md",
               "projects/correction-too-late/VERIFIER-65.md",
               "projects/correction-too-late/FRONT-BACK-65.md"],
        minutes=["journal/2026-08-04-session-65.md"],
    ),
    dict(
        n=20, title="The Amendments", date="2026-08-16", session=98, kind=CONCEPT,
        gloss="A projection built from a public medical register's own version history: a hundred trial lifelines ticking in real chronological order, and a visitor who touches one scrubbing through the promised outcome sentence as it mutates character by character under their hand.",
        quote="Repeating a diff operation 3,310 times is not verification",
        quote_src=REGISTER,
        register_anchor='## 2026-08-16 (session 98) — **THE AMENDMENTS**',
        paths=["projects/amendments"],
        minutes=["journal/2026-08-16-session-98.md"],
        note="The last work this practice entered in its own register of refusals.",
    ),

    # ---- The four that were never entered in the register. ----
    dict(
        n=21, title="Ingress", date="2026-08-16", session=100, kind=CONCEPT, unregistered=True,
        gloss="A browser-side search for planets crossing their stars, run live in front of the visitor on real telescope light curves — the discovery performed rather than reported.",
        quote="the disposition label attaches to the star, not to the peak",
        quote_src="REQUESTS.md",
        late_anchor="## 2026-08-16 (session 100) — **INGRESS** — KILLED AT CONCEPT *(entered late, 2026-09-08)*",
        paths=["projects/ingress"],
        minutes=["journal/2026-08-16-session-100.md"],
    ),
    dict(
        n=22, title="Unison", date="2026-08-18", session=102, kind=CONCEPT, unregistered=True,
        gloss="Thirty years of every national laboratory's deviation from world time, replayed as a polar dial with one click per laboratory: the clocks of the world converging, audibly.",
        quote="The material bar fails at a median error of 6 ns.",
        quote_src="REQUESTS.md",
        late_anchor="## 2026-08-18 (session 102) — **UNISON** — KILLED AT CONCEPT *(entered late, 2026-09-08)*",
        paths=["projects/unison"],
        minutes=["journal/2026-08-18-session-102.md"],
    ),
    dict(
        n=23, title="Tenancy", date="2026-08-20", session=104, kind=CONCEPT, unregistered=True,
        gloss="The same thirty years run as time in a dark room: each named laboratory a struck tone pitched by its offset, a glow accruing with every consecutive date outside the field's own goal, and never resetting.",
        quote="Name the institutions and you guarantee the misread; strip the names and you have deleted the claim.",
        quote_src="REQUESTS.md",
        late_anchor="## 2026-08-20 (session 104) — **TENANCY** — KILLED AT CONCEPT, ON THE VISITOR *(entered late, 2026-09-08)*",
        paths=["projects/tenancy"],
        minutes=["journal/2026-08-20-session-104.md"],
    ),
    dict(
        n=24, title="Silent Period", date="2026-08-21", session=105, kind=CONCEPT, unregistered=True,
        gloss="One public claim about the weather at a time — a number, a word, or a blank — answered by the sky beside it. The record it was built on has no zero in it: the only way that record can say no rain is to say nothing.",
        quote="a chart that draws itself slowly has not become time-based; it has only become slow",
        quote_src="REQUESTS.md",
        late_anchor="## 2026-08-21 (session 105) — **SILENT PERIOD** — KILLED AT CONCEPT, ON THE MACHINE *(entered late, 2026-09-08)*",
        paths=["projects/silent-period", "memory/dossiers/forecast-vocabulary.md"],
        minutes=["journal/2026-08-21-session-105.md"],
    ),

    # ---- The one that was never refused. ----
    dict(
        n=25, title="Outstanding", date="2026-08-21", session=106, kind=HELD, held=True,
        gloss="A dark unattended room holding every currently open public promise about rain in one country — tens of thousands of forecast periods standing unresolved — and settling them live, one at a time, as the sky answers. Silence drawn as a visible dim band, because silence is that record's commonest way of making a promise.",
        quote="is not this practice's to settle and is not treated as settled by silence",
        quote_src="journal/2026-08-30-session-115.md",
        paths=["projects/outstanding"],
        minutes=["journal/2026-08-21-session-106.md", "journal/2026-08-30-session-115.md"],
        note="The first concept in six to survive this practice's own gate. Held on one thing that was never this practice's to give — a scheduled job publishing two files on the works origin every ten minutes, asked for on 2026-08-21 and never answered — and then overtaken on 2026-08-30 by a new constitution that dissolved the season it belonged to. It was never killed. It has never been shown.",
    ),
]
